### ISSUE TITLE
RawNode::with_default_logger() panics on Option::unwrap()

### ISSUE THREAD

**Issue by Licenser** [tikv/raft-rs#312]
**Describe the bug**
RawNode::with_default_logger() panics on Option::unwrap()

```
  12: raft::default_logger
             at src/lib.rs:594
  13: raft::raw_node::RawNode<T>::with_default_logger
             at src/raw_node.rs:246
```
**To Reproduce**
call `RawNode::with_default_logger()`

**Expected behavior**
It creates a default logger without panicing

**Comment by Hoverbear** [comment]
I tested this on `master` by creating `examples/logger.rs`:

```rust
use raft::{
    Config,
    storage::MemStorage,
    raw_node::RawNode,
};

fn main() {
    // Select some defaults, then change what we need.
    let config = Config {
        id: 1,
        ..Default::default()
    };
    // ... Make any configuration changes.
    // After, make sure it's valid!
    config.validate().unwrap();
    // We'll use the built-in `MemStorage`, but you will likely want your own.
    // Finally, create our Raft node!
    let storage = MemStorage::new_with_conf_state((vec![1], vec![]));
    let mut node = RawNode::with_default_logger(&config, storage).unwrap();
    // We will coax it into being the lead of a single node cluster for exploration.
    node.raft.become_candidate();
    node.raft.become_leader();
}
```

Then I ran it:

```powershell
PS C:\Users\Hoverbear\Git\raft-rs> $Env:RUST_LOG="raft=trace"
PS C:\Users\Hoverbear\Git\raft-rs> cargo run --example logger
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target\debug\examples\logger.exe`
case: main
 raft_id: 1
  Oct 31 13:52:54.907 DEBG Inserting voter with id 1, id: 1
  Oct 31 13:52:54.917 DEBG reset election timeout 0 -> 28 at 0, election_elapsed: 0, timeout: 28, prev_timeout: 0
  Oct 31 13:52:54.928 INFO became follower at term 1, term: 1
  Oct 31 13:52:54.945 INFO newRaft, pending membership change: None, peers: [(1, Progress { matched: 1, next_idx: 2, state: Probe, paused: false, pending_snapshot: 0, pending_request_snapshot: 0, recent_active: false, ins: Inflights { start: 0, count: 0, buffer: [] } })], last term: 1, last index: 1, applied: 1, commit: 1, term: 1
  Oct 31 13:52:54.977 INFO RawNode created with id 1., id: 1
  Oct 31 13:52:54.983 DEBG reset election timeout 28 -> 35 at 0, election_elapsed: 0, timeout: 35, prev_timeout: 28
  Oct 31 13:52:54.994 INFO became candidate at term 2, term: 2
  Oct 31 13:52:54.999 DEBG reset election timeout 35 -> 29 at 0, election_elapsed: 0, timeout: 29, prev_timeout: 35
  Oct 31 13:52:55.011 DEBG committing index 2, index: 2
  Oct 31 13:52:55.028 INFO became leader at term 2, term: 2
```

Can you please specify your version, provide a full error log, or reproduction case?

**Comment by Licenser** [comment]
reproduction:
https://github.com/wayfair-incubator/uring/tree/logger-crash
crashs with:
```bash
cargo run -- -e 127.0.0.1:8081 -i 01
```

**Comment by Hoverbear** [comment]
OK! I see what's happening now. :)

```
hoverbear@Obsidian:~/git/uring$ RUST_BACKTRACE=1 RUST_LOG=raft=trace cargo run -- -e 127.0.0.1:8081 -i 01 
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/uring -e '127.0.0.1:8081' -i 01`
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  14: core::panicking::panic
             at src/libcore/panicking.rs:49
  15: core::option::Option<T>::unwrap
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/macros.rs:12
  16: raft::default_logger
             at /home/hoverbear/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2ce67a0/src/lib.rs:594
  17: raft::raw_node::RawNode<T>::with_default_logger
             at /home/hoverbear/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2ce67a0/src/raw_node.rs:246
  18: uring::raft_node::RaftNode::create_raft_leader
             at src/raft_node.rs:170
  19: uring::loopy_thing
             at src/main.rs:424
  20: uring::main::{{closure}}
             at src/main.rs:693
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


hoverbear@Obsidian:~/git/uring$ ^C
```

The key bit is:

```
  16: raft::default_logger
             at /home/hoverbear/.cargo/git/checkouts/raft-rs-42b8049ef2e3af07/2ce67a0/src/lib.rs:594
```

Which points us to:

https://github.com/tikv/raft-rs/blob/faa4384d2ed2458279403de1dfef5e160e9ed9f9/src/lib.rs#L594-L600

I'll make a patch to make refactor this. :) In the meantime I suggest the workaround of giving your thread a name (`raft::dummy` should be sufficient.)

**Comment by Licenser** [comment]
Oh thanks! I didn't find that :D thanks! Already worked around it by initializing a logger that solved it too - wanted to report it non the less.

**Comment by Hoverbear** [comment]
Hey of course. :) Let us know if you have more trouble, really great to see folks using the library as well and reporting issues!
